import {
  Event,
  TeamMember,
  Announcement,
  GalleryAlbum,
  GalleryMedia,
  CommunityStatistics,
  CommunitySettings,
  EventSponsor,
  ContactMessage,
  ActivityLog,
} from '../types';

export const INITIAL_SETTINGS: CommunitySettings = {
  id: '1',
  website_name: 'CodeRush',
  tagline: 'Official Technical Community of BBDNIIT',
  about: 'CodeRush is the flagship technical community at Babu Banarasi Das Northern India Institute of Technology (BBDNIIT), Lucknow. We foster student developer ecosystems, host flagship hackathons, conduct hands-on workshops, and bridge academia with tech industry standards.',
  email: 'coderush.bbdniit@gmail.com',
  phone: '+91 98765 43210',
  address: 'BBDNIIT Campus, BBD Educational City, Faizabad Road, Lucknow, UP - 226028',
  instagram: 'https://instagram.com/coderush_bbdniit',
  linkedin: 'https://linkedin.com/company/coderush-bbdniit',
  github: 'https://github.com/coderush-bbdniit',
  youtube: 'https://youtube.com/@coderush_bbdniit',
  hero_title: 'CODERUSH',
  hero_subtitle: 'Official Technical Community of BBDNIIT',
  hero_description: 'Empowering student developers, innovators, and creators through national hackathons, technical bootcamps, and industry mentorship.',
  footer_text: 'Building professional digital identities & empowering future engineering leaders at BBDNIIT.',
};

export const INITIAL_STATISTICS: CommunityStatistics = {
  id: '1',
  students_reached: 2800,
  community_members: 1450,
  events: 22,
  hackathons: 6,
  workshops: 14,
  organizers: 42,
  projects: 98,
  sponsors: 18,
};

export const INITIAL_EVENTS: Event[] = [
  {
    id: 'evt-1',
    title: 'CodeRush 3.0: National Flagship Hackathon',
    slug: 'coderush-3-0',
    short_description: '36-Hour non-stop physical hackathon bringing 500+ builders to solve real-world problems in AI, Web3, FinTech, and IoT.',
    full_description: 'CodeRush 3.0 is the premier national hackathon hosted by BBDNIIT. Over 36 hours, top developer teams across India will build innovative solutions, interact with industry mentors, present before distinguished judges, and compete for a total prize pool of ₹1,50,000.',
    poster: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&q=80&w=1200',
    cover_image: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&q=80&w=1600',
    category: 'Hackathon',
    mode: 'In-Person',
    venue: 'Main Auditorium, BBDNIIT Campus',
    city: 'Lucknow',
    state: 'Uttar Pradesh',
    country: 'India',
    registration_link: 'https://forms.google.com/example-coderush3',
    feedback_link: 'https://forms.google.com/example-coderush3-feedback',
    reveal_date: '2026-07-01T00:00:00Z',
    registration_start: '2026-07-10T00:00:00Z',
    registration_end: '2026-08-25T23:59:59Z',
    event_start: '2026-09-10T09:00:00Z',
    event_end: '2026-09-11T21:00:00Z',
    publish_status: true,
    featured: true,
    gallery_published: true,
    registration_enabled: true,
    status: 'registration_open',
    meta_title: 'CodeRush 3.0 | 36-Hour National Hackathon at BBDNIIT',
    meta_description: 'Register for CodeRush 3.0, the flagship 36-hour national hackathon presented by CodeRush BBDNIIT.',
    keywords: 'CodeRush, BBDNIIT, Hackathon, Lucknow, Developer Community',
    created_at: '2026-06-15T10:00:00Z',
    updated_at: '2026-07-10T10:00:00Z',
    statistics: {
      id: 'stat-1',
      event_id: 'evt-1',
      participants: 520,
      volunteers: 35,
      organizers: 25,
      judges: 8,
      mentors: 12,
      projects: 86,
      teams: 110,
      colleges: 24,
      sponsors: 7,
      certificates: 520,
      hours: 36,
      prize_pool: '₹1,50,000',
    },
    timeline: [
      { id: 't-1', event_id: 'evt-1', title: 'Registration Opens', description: 'Early bird applications open online', event_time: '2026-07-10T00:00:00Z', display_order: 1 },
      { id: 't-2', event_id: 'evt-1', title: 'Check-In & Opening Ceremony', description: 'Participant briefing & keynotes', event_time: '2026-09-10T09:00:00Z', display_order: 2 },
      { id: 't-3', event_id: 'evt-1', title: 'Hacking Begins', description: 'Clock starts for 36 continuous hours', event_time: '2026-09-10T11:00:00Z', display_order: 3 },
      { id: 't-4', event_id: 'evt-1', title: 'Mentorship Round 1', description: 'Technical guidance from industry experts', event_time: '2026-09-10T17:00:00Z', display_order: 4 },
      { id: 't-5', event_id: 'evt-1', title: 'Final Pitching & Demos', description: 'Top 15 teams present to jury', event_time: '2026-09-11T16:00:00Z', display_order: 5 },
      { id: 't-6', event_id: 'evt-1', title: 'Prize Ceremony', description: 'Winners announced and felicitated', event_time: '2026-09-11T19:30:00Z', display_order: 6 },
    ],
    schedule: [
      { id: 's-1', event_id: 'evt-1', day: 'Day 1', time: '09:00 AM - 10:30 AM', session_title: 'Check-in & Welcome Kit Distribution', venue: 'Auditorium Foyer', display_order: 1 },
      { id: 's-2', event_id: 'evt-1', day: 'Day 1', time: '11:00 AM', session_title: 'Hacking Launch & Problem Statements Reveal', venue: 'Main Hall', display_order: 2 },
      { id: 's-3', event_id: 'evt-1', day: 'Day 2', time: '04:00 PM - 06:00 PM', session_title: 'Grand Finale Evaluations', venue: 'Seminar Hall A', display_order: 3 },
    ],
    rules: [
      { id: 'r-1', event_id: 'evt-1', rule: 'Teams can have 2 to 4 members. Inter-college teams are allowed.', display_order: 1 },
      { id: 'r-2', event_id: 'evt-1', rule: 'All code must be written during the 36-hour hackathon period.', display_order: 2 },
      { id: 'r-3', event_id: 'evt-1', rule: 'Participants must strictly abide by the CodeRush Code of Conduct.', display_order: 3 },
    ],
    faqs: [
      { id: 'f-1', event_id: 'evt-1', question: 'Is there any registration fee?', answer: 'No, participation in CodeRush 3.0 is completely free of cost for all shortlisted students.', display_order: 1 },
      { id: 'f-2', event_id: 'evt-1', question: 'Will food and accommodation be provided?', answer: 'Yes! Free meals, refreshments, energy drinks, and resting zones are provided on campus.', display_order: 2 },
    ],
    sponsors: [
      { id: 'sp-1', event_id: 'evt-1', sponsor_name: 'GitHub', logo: 'https://github.githubassets.com/assets/GitHub-Mark-ea2971500d4d.png', website: 'https://github.com', tier: 'Title Sponsor', display_order: 1 },
      { id: 'sp-2', event_id: 'evt-1', sponsor_name: 'Devfolio', logo: 'https://assets.devfolio.co/brand/devfolio-logo.png', website: 'https://devfolio.co', tier: 'Gold', display_order: 2 },
    ],
    winners: [
      { id: 'w-1', event_id: 'evt-1', position: 'Winner (1st Rank)', team_name: 'CyberCrafters', members: 'Aarav Sharma, Ananya Verma', college: 'BBDNIIT', project: 'AI Medical Triage System', photo: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&q=80&w=600', description: 'Built a real-time computer vision emergency triage assistant.' }
    ]
  },
  {
    id: 'evt-2',
    title: 'Full-Stack Web Development Bootcamp',
    slug: 'web-dev-bootcamp-2026',
    short_description: '3-Day intensive hands-on workshop covering React, Next.js, Node.js, and modern UI engineering principles.',
    full_description: 'Master industry-grade full-stack web development with CodeRush core leads. Learn modern React patterns, responsive dark UI design systems, REST & GraphQL APIs, and Vercel deployment workflows.',
    poster: 'https://images.unsplash.com/photo-1531403009284-440f080d1e12?auto=format&fit=crop&q=80&w=1200',
    cover_image: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&q=80&w=1600',
    category: 'Workshop',
    mode: 'In-Person',
    venue: 'Computer Lab 3, Department of CSE',
    city: 'Lucknow',
    state: 'Uttar Pradesh',
    country: 'India',
    registration_link: 'https://forms.google.com/example-webdev',
    event_start: '2026-08-15T10:00:00Z',
    event_end: '2026-08-17T16:00:00Z',
    publish_status: true,
    featured: false,
    gallery_published: false,
    registration_enabled: true,
    status: 'coming_soon',
    created_at: '2026-07-20T10:00:00Z',
    updated_at: '2026-07-20T10:00:00Z',
  },
  {
    id: 'evt-3',
    title: 'CodeRush 2.0: Winter Hackathon',
    slug: 'coderush-2-0',
    short_description: 'Past flagship hackathon with 400+ attendees, 60 projects submitted, and top industry judges.',
    full_description: 'CodeRush 2.0 witnessed ground-breaking projects built across 24 continuous hours. Highlights include cloud-native solutions, IoT hardware demos, and AI agents.',
    poster: 'https://images.unsplash.com/photo-1515187029135-18ee286d815b?auto=format&fit=crop&q=80&w=1200',
    cover_image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&q=80&w=1600',
    category: 'Hackathon',
    mode: 'In-Person',
    venue: 'Main Auditorium, BBDNIIT',
    city: 'Lucknow',
    event_start: '2025-11-20T10:00:00Z',
    event_end: '2025-11-21T18:00:00Z',
    publish_status: true,
    featured: false,
    gallery_published: true,
    registration_enabled: false,
    status: 'completed',
    created_at: '2025-10-01T10:00:00Z',
    updated_at: '2025-11-25T10:00:00Z',
    statistics: {
      id: 'stat-3',
      event_id: 'evt-3',
      participants: 410,
      volunteers: 28,
      organizers: 20,
      judges: 6,
      mentors: 10,
      projects: 64,
      teams: 92,
      colleges: 18,
      sponsors: 5,
      certificates: 410,
      hours: 24,
      prize_pool: '₹1,00,000',
    },
    winners: [
      { id: 'w-31', event_id: 'evt-3', position: '1st Place Winner', team_name: 'DevDynamos', members: 'Rohan Gupta, Priya Singh', college: 'BBDNIIT', project: 'Smart AgriSense IoT', photo: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&q=80&w=600', description: 'IoT based automated crop health monitor.' }
    ]
  }
];

export const INITIAL_TEAM: TeamMember[] = [
  {
    id: 'tm-1',
    name: 'Dr. Anurag Shrivastava',
    role: 'Faculty Coordinator',
    department: 'Computer Science & Engineering',
    year: 'Faculty',
    photo: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=600',
    bio: 'Guiding CodeRush vision and driving academic-industry partnerships at BBDNIIT.',
    linkedin: 'https://linkedin.com',
    email: 'anurag.shrivastava@bbdniit.ac.in',
    display_order: 1,
    featured: true,
    is_top_leader: true,
    is_active: true,
  },
  {
    id: 'tm-2',
    name: 'Shubhang Srivastava',
    role: 'Technical Lead & Lead Architect',
    department: 'Information Technology',
    year: '4th Year',
    photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=600',
    bio: 'Full-stack software engineer & community lead. Architected CodeRush digital platform.',
    linkedin: 'https://linkedin.com/in/shubhang-srivastava',
    github: 'https://github.com/shubhang-srivastava',
    email: 'shubhang.dev@gmail.com',
    display_order: 2,
    featured: true,
    is_top_leader: true,
    is_active: true,
  },
  {
    id: 'tm-3',
    name: 'Riddhi Patel',
    role: 'Community Co-Coordinator',
    department: 'Computer Science & Engineering',
    year: '4th Year',
    photo: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=600',
    bio: 'Managing community events, sponsor relations, and event execution.',
    linkedin: 'https://linkedin.com',
    github: 'https://github.com',
    email: 'riddhi.coderush@gmail.com',
    display_order: 3,
    featured: true,
    is_active: true,
  },
  {
    id: 'tm-4',
    name: 'Aditya Raj',
    role: 'Design & UI/UX Lead',
    department: 'Computer Science',
    year: '3rd Year',
    photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=600',
    bio: 'Crafting premium visual identities, posters, dark mode UI design systems.',
    linkedin: 'https://linkedin.com',
    github: 'https://github.com',
    display_order: 4,
    featured: false,
    is_active: true,
  },
  {
    id: 'tm-5',
    name: 'Kavya Singh',
    role: 'PR & Outreach Lead',
    department: 'Information Technology',
    year: '3rd Year',
    photo: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=600',
    bio: 'Leading social media outreach, college ambassador network, and sponsor communications.',
    linkedin: 'https://linkedin.com',
    display_order: 5,
    featured: false,
    is_active: true,
  }
];

export const INITIAL_ANNOUNCEMENTS: Announcement[] = [
  {
    id: 'ann-1',
    title: 'CodeRush Core Team Recruitment 2026-27 Announced!',
    description: 'We are expanding our organizing team! Applications are open for Technical, Design, Operations, and PR leads.',
    badge: 'Recruitment',
    button_text: 'Apply for Core Team',
    button_link: 'https://forms.google.com/example-recruitment',
    publish_date: '2026-08-01T00:00:00Z',
    expiry_date: '2026-08-30T23:59:59Z',
    priority: 1,
    published: true,
  },
  {
    id: 'ann-2',
    title: 'CodeRush 3.0 Hackathon Registrations are NOW LIVE!',
    description: 'Register your team before August 25th for the biggest 36-hour hackathon at BBDNIIT.',
    badge: 'Registration',
    button_text: 'Register Now',
    button_link: '/events/coderush-3-0',
    publish_date: '2026-07-10T00:00:00Z',
    expiry_date: '2026-08-25T23:59:59Z',
    priority: 2,
    published: true,
  }
];

export const INITIAL_ALBUMS: GalleryAlbum[] = [
  {
    id: 'alb-1',
    title: 'CodeRush 2.0 Highlights',
    slug: 'coderush-2-0-gallery',
    cover_image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&q=80&w=1200',
    description: 'Official high-resolution memory archive from CodeRush 2.0 Winter Hackathon.',
    event_id: 'evt-3',
    display_order: 1,
    published: true,
    media_count: 6,
  }
];

export const INITIAL_GALLERY_MEDIA: GalleryMedia[] = [
  {
    id: 'gm-1',
    album_id: 'alb-1',
    media_type: 'image',
    file_url: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&q=80&w=1200',
    caption: 'Hackers coding in the main hall during Midnight Sprint',
    display_order: 1,
  },
  {
    id: 'gm-2',
    album_id: 'alb-1',
    media_type: 'image',
    file_url: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&q=80&w=1200',
    caption: 'Mentorship round session with tech leaders',
    display_order: 2,
  },
  {
    id: 'gm-3',
    album_id: 'alb-1',
    media_type: 'image',
    file_url: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&q=80&w=1200',
    caption: 'Winning team receiving trophy on stage',
    display_order: 3,
  }
];

export const INITIAL_SPONSORS: EventSponsor[] = [
  {
    id: 'sp-101',
    sponsor_name: 'GitHub',
    logo: 'https://github.githubassets.com/assets/GitHub-Mark-ea2971500d4d.png',
    website: 'https://github.com',
    tier: 'Title Sponsor',
    description: 'Global developer platform supporting open source student developer ecosystems.',
    display_order: 1,
  },
  {
    id: 'sp-102',
    sponsor_name: 'Vercel',
    logo: 'https://assets.vercel.com/image/upload/v1588805858/repositories/vercel/logo.png',
    website: 'https://vercel.com',
    tier: 'Gold',
    description: 'Frontend cloud platform powering seamless production web deployments.',
    display_order: 2,
  }
];

export const INITIAL_MESSAGES: ContactMessage[] = [
  {
    id: 'msg-1',
    name: 'Siddharth Roy',
    email: 'siddharth@example.com',
    subject: 'Sponsorship Inquiry for CodeRush 3.0',
    message: 'Hello CodeRush team, our company would like to explore gold tier sponsorship for your upcoming hackathon. Please get in touch.',
    status: 'unread',
    created_at: '2026-08-05T14:30:00Z',
  }
];

export const INITIAL_ACTIVITY_LOGS: ActivityLog[] = [
  {
    id: 'log-1',
    action: 'Event Updated',
    details: 'CodeRush 3.0 registration link updated by Super Admin',
    admin_name: 'CoderushOfficials',
    created_at: '2026-08-06T12:00:00Z',
  }
];
